 ##############################################################################
 # Student Name    : Victor Ageev
 # RMIT Student ID : s3732094
 # COURSE CODE     : CPT220
 #
 # Startup code provided by Paul Miller for use in "Programming in C",
 # study period 4, 2018.
 ##############################################################################

picedit2: command.c fileio.c helpers.c line.c main.c repl.c safemalloc.c
	gcc -ansi -pedantic command.c fileio.c helpers.c line.c main.c safemalloc.c repl.c -o picedit2 -g3



